# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
#  config.vm.box = "ubuntu/xenial64"
  config.vm.box = "centos/7"
  config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.synced_folder "../../../..", "/vagrant-code"
  config.vm.provision :shell, path: "vagrant-provision.sh"
end
